modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="natural_energy_mod"
version="1.0.0"
displayName="natural energy mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="sylvi, MCreator"

[[dependencies.natural_energy_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




